# Generated by Django 5.2.4 on 2025-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('seats', models.PositiveIntegerField()),
            ],
        ),
    ]
